### ISSUE TITLE
Recent update causes error on sslmode #291

### ISSUE THREAD

**Issue by statzhero** [trr266/treat#3]
I had to debug a postgres [error](https://github.com/r-dbi/RPostgres/issues/291). 

I believe the template loads the CRAN version, but whether this is just a local issue I have no idea. 

I expect this to go away soon, but for anyone else struggling: the solution was to reinstall `RPostgres` from source.

```
install.packages("RPostgres", repos = "https://r-dbi.r-universe.dev")
```

**Comment by joachim-gassen** [comment]
Jepp. That what useful back in the days but now CRAN should be fine again. Thanks!
