### ISSUE TITLE
Calibri font on macos

### ISSUE THREAD

**Issue by harrynnh** [trr266/treat#6]
Hi all,
I encountered a Calibri font missing issue when producing outputs on macos. Simply got rid of it by commenting out \setsansfont{Calibri} in beamer_theme_trr266.sty. Would you suggest doing something else to make this run across operating systems?
Thanks,
Harry

**Comment by joachim-gassen** [comment]
Sorry for the delay (haha...) but in a more general effort to increase portability I also added some code that falls back to Google's open source Carlito font whenever Calibri is not available (836eb7c). Thanks for pointing this out!
